
import { Employee, Material, Rig, Admin } from './types';

export const RIGS: Rig[] = [
  { id: 'S01', name: 'Sonda Alpha 01', location: 'Bacia de Campos' },
  { id: 'S02', name: 'Sonda Beta 02', location: 'Bacia de Santos' },
  { id: 'S03', name: 'Sonda Gamma 03', location: 'Onshore - Bahia' },
  { id: 'SPT01', name: 'SPT PR 01', location: 'RN - Mossoró' },
  { id: 'SPT03', name: 'SPT PR 03', location: 'RN - Areia Branca' },
  { id: 'SPT25', name: 'SPT PR 25', location: 'RN - Pendências' },
];

export const INITIAL_ROLES: string[] = [
  'Plataformista', 
  'Torrista', 
  'Sondador', 
  'Mecânico', 
  'Eletricista', 
  'Gerente',
  'Supervisor de Sonda',
  'Supervisor de Sondas',
  'Operador Técnico de Sonda I',
  'Operador Técnico de Sonda II',
  'Operador-Tecnico de Sondas I',
  'Operador-Tecnico de Sondas II',
  'Auxiliar de Operacao de Sonda',
  'Operador-Tecnico de Elevacao I',
  'Operador-Tecnico de Elevacao II',
  'Operador-Tecnico de Guindauto de Elevacao',
  'Analista de SMS',
  'Engenheiro de Segurança',
  'Médico do Trabalho',
  'Técnico de Infraestrutura TI',
  'Almoxarife',
  'Engenheiro de Campo',
  'Técnico de Planejamento I',
  'Técnico de Planejamento II',
  'Estagiário'
];

/**
 * Relação de colaboradores extraída da lista anexa (Amostra de todas as páginas)
 * Formato: [Matrícula, Nome, Função]
 */
const RAW_EMPLOYEES_DATA: [string, string, string][] = [
  // Página 1
  ['001168', 'EILSON LOPES MORAIS FILHO', 'COORDENADOR DE SAUDE E SEGURANCA'],
  ['002205', 'CLARA NIVEA COSTA DO VALE', 'ENGENHEIRO DE SEGURANCA DO TRABALHO I'],
  ['002208', 'KARINE DE LIMA ISALTO', 'ANALISTA DE SAUDE E SEGURANCA I'],
  ['002232', 'VINNICIUS HENRIQUE NOBERTO DE MELO', 'AUXILIAR ADMINISTRATIVO'],
  ['003054', 'LUANA MARIELLE DAMASIO MOURA', 'ENGENHEIRO DE SEGURANCA DO TRABALHO I'],
  ['002580', 'TADEU MONTEIRO CABRAL', 'TECNICO DE SEGURANCA DO TRABALHO II'],
  ['002285', 'JOSE GILGAMES OLIVEIRA FILGUEIRA', 'TECNICO DE SEGURANCA DO TRABALHO II'],
  ['002501', 'JEANILSON DE MEDEIROS', 'TECNICO DE SEGURANCA DO TRABALHO I'],
  ['002387', 'FRANCISCO RAIMUNDO DA SILVA FILHO', 'TECNICO DE SEGURANCA DO TRABALHO II'],
  ['003001', 'PEDRO LUCAS DE MOURA FREITAS', 'TECNICO DE SEGURANCA DO TRABALHO I'],
  ['002930', 'RAFAEL TAIRONE DA ROCHA', 'TECNICO DE SEGURANCA DO TRABALHO I'],
  ['003000', 'RANIELLY REGINA DA SILVA', 'ENFERMEIRO DO TRABALHO'],
  ['002954', 'OLIVIA DE ARAUJO PAULA', 'MEDICO DO TRABALHO'],
  ['002053', 'MAYARA RICELLY DE OLIVEIRA LEITE DE MELO', 'COORDENADOR DE SSMS'],
  ['002507', 'FABIANA DO NASCIMENTO SANTOS', 'ENGENHEIRO DE SEGURANCA DE PROCESSO III'],
  ['002435', 'DIANE GOMES DE MEDEIROS', 'ENGENHEIRO DE SEGURANCA DE PROCESSO II'],
  ['003063', 'SAMANTHA ELOY SILVA', 'ENGENHEIRO DE SEGURANCA DE PROCESSO I'],
  ['002319', 'CAIO ISRAEL DA SILVA', 'TECNICO DE SEGURANCA DO TRABALHO II'],
  ['002117', 'DOUGLAS DE SOUSA ALVES', 'SUPERVISOR DE INFRAESTRUTURA DE TI'],
  ['002227', 'IGOR DE MORAES MENDES', 'TECNICO DE INFRAESTRUTURA E SUPORTE DE TI'],
  ['002061', 'FELIPE CESAR ALVES DO COUTO', 'COORDENADOR DE INFRAESTRUTURA DE AUTOMACAO'],
  ['003082', 'SERGIO FRANCISCO DE JESUS', 'OPERADOR-TECNICO DE ELEVACAO I'],
  ['003085', 'UELINGTON SANTANA DOS SANTOS', 'OPERADOR-TECNICO DE ELEVACAO II'],
  ['003081', 'ALFREDO DOS SANTOS FILHO', 'OPERADOR-TECNICO DE GUINDAUTO DE ELEVACAO'],

  // Página 2
  ['002537', 'ADRIANO ARAUJO NERIS', 'SUPERVISOR DE SONDAS'],
  ['002612', 'FRANCISCO ERIONE PINTO MOREIRA', 'SUPERVISOR DE SONDAS'],
  ['002354', 'JOSE LUZAIDY LIMA DE MEDEIROS', 'OPERADOR-TECNICO DE SONDAS I'],
  ['002305', 'CARLOS ALBERTO DE ARAUJO', 'PLATAFORMISTA'],
  ['002591', 'JOAO FERNANDES BRAGA NETO', 'OPERADOR-TECNICO DE SONDAS I'],
  ['002427', 'WELLINGTON MENDES DA SILVA', 'TORRISTA'],
  ['002159', 'CRISTIANO RODRIGUES DE LIMA', 'OPERADOR-TECNICO DE SONDAS I'],
  ['003116', 'YTALO ISRAEL BRITO PINHEIRO', 'AUXILIAR DE OPERACAO DE SONDA'],
  ['800319', 'GIOVANA SOARES DANTAS ALVES DA SILVA', 'ESTAGIARIO'],

  // Página 3
  ['003125', 'FABIO HENRIQUE ALVES DE OLIVEIRA', 'PLATAFORMISTA'],
  ['002185', 'HAROLDO CAMARA DA ROCHA', 'OPERADOR-TECNICO DE SONDAS I'],
  ['002211', 'FRANCISCO VALTERNANE DE MELO', 'OPERADOR-TECNICO DE SONDAS I'],
  ['002174', 'LUIZ RODRIGUES LOPES NETO', 'SUPERVISOR DE SONDAS'],
  ['003167', 'LUIZ KLEBER FERNANDES DE SOUSA', 'SUPERVISOR DE SONDAS'],
  ['002069', 'JEFFERSON TAYRONE SILVA FRANCA', 'OPERADOR-TECNICO DE SONDAS I'],
  ['002114', 'ABRAHAO FELIPE DE QUEIROZ', 'OPERADOR-TECNICO DE SONDAS II'],

  // Página 4
  ['002509', 'JEFFERSON SANTOS DE LIMA', 'TORRISTA'],
  ['002534', 'LUIKSON BARBOSA DE MOURA', 'PLATAFORMISTA'],
  ['002088', 'GILTEMAR BEZERRA DA SILVA', 'SUPERVISOR DE SONDAS'],
  ['003095', 'FABIO CIDREIRA GUIMARAES', 'SUPERVISOR DE SONDAS'],
  ['002080', 'JOSEANO CANDIDO DE MEDEIROS', 'SUPERVISOR DE ELEVACAO'],

  // Página 5
  ['002051', 'NAILSON BARBOSA DA SILVA', 'OPERADOR-TECNICO DE GUINDAUTO DE ELEVACAO'],
  ['002056', 'JUSCELINO LOPES DA COSTA', 'SUPERVISOR DE SONDAS'],
  ['003142', 'MOACIR SANTOS MOURA', 'SUPERVISOR DE SONDAS'],
  ['002034', 'LUIZ SERGIO PINHEIRO DA COSTA JUNIOR', 'ESPECIALISTA DE INTERVENCAO'],
  ['002039', 'GETHERO LUIZ TELLES SANTOS', 'COORDENADOR DE SONDA'],
  ['002338', 'BARBARA NAYANE OLIVEIRA DE SALES', 'ENGENHEIRO DE CAMPO'],
  ['002029', 'JALMA GOMES RIOS', 'ENGENHEIRO DE CAMPO'],

  // Página 6
  ['002853', 'EDICLAUDIO CUNHA DO NASCIMENTO', 'SUPERVISOR DE SONDAS'],
  ['002573', 'MARINALDO DOS SANTOS REGIS', 'OPERADOR-TECNICO DE SONDAS II'],
  ['002037', 'FRANCISCO SARVIO DA COSTA CAMARA', 'GERENTE DE SERVICO'],
  ['002206', 'MAYLA ALENCAR MEDEIROS', 'ENGENHEIRO DE CAMPO'],
  ['002260', 'DYANA ALVES DE OLIVEIRA', 'ENGENHEIRO DE CAMPO'],

  // Página 7
  ['002028', 'ANDERSON LIMA SANTANA', 'SUPERVISOR INSPECAO'],
  ['002121', 'MICARLA GURGEL BENEVIDES', 'SUPERVISOR DE LABORATORIO'],
  ['002072', 'JOAO BATISTA BENEDITO VIEIRA', 'SUPERVISOR DE MANUTENCAO'],
  ['002172', 'WENDEL DE MACEDO ROCHA', 'SUPERVISOR DE SERVICOS'],

  // Página 8
  ['002252', 'ANTONIO JOSENILDO BATISTA', 'SUPERVISOR DE MANUTENCAO DE SONDA'],
  ['002596', 'AILTON RODRIGUES DO ROSARIO', 'SOLDADOR'],

  // Página 9
  ['002169', 'RICARDO TATUO YODA', 'SUPERVISOR DE MANUTENCAO DE SONDA'],
  ['002153', 'JOSE CICERO DA SILVA SANTOS FILHO', 'SUPERVISOR DE MANUTENCAO DE SONDA'],
  ['002251', 'ALEXANDRE DA CRUZ PEREIRA', 'SUPERVISOR DE MANUTENCAO DE SONDA'],
  ['002237', 'FREDERICO DE PAULA TORRES', 'ENGENHEIRO MECANICO DE MANUTENCAO DE SONDA II'],
  ['002511', 'JONATHAN ROSSI DE OLIVEIRA', 'ENGENHEIRO MECANICO DE MANUTENCAO DE SONDA II'],
  ['002398', 'ALBENI GURGEL FERREIRA JUNIOR', 'ENGENHEIRO MECANICO DE MANUTENCAO DE SONDA II'],

  // Página 10
  ['002042', 'ALISON AUGUSTO MAIA BEZERRA', 'GERENTE DE POLO'],
  ['002582', 'LINDAIANA MARIA DE MEDEIROS', 'SUPERVISOR DE PRODUCAO'],
  ['002128', 'THIAGO VINICIUS FERNANDES CARVALHO', 'SUPERVISOR DE PRODUCAO'],
  ['002068', 'JOSE ANTONIO GAMA JUNIOR', 'GERENTE DE POLO'],

  // Página 11 a 16 (Destaques)
  ['002546', 'ISRAEL CLEVIS ALVES RIBEIRO', 'SUPERVISOR DE PRODUCAO'],
  ['002026', 'MILTON SOUZA BRITO NETO', 'SUPERVISOR DE PRODUCAO'],
  ['002110', 'ANDRE MAGNO DA SILVA', 'SUPERVISOR DE PRODUCAO'],
  ['002140', 'RAIMUNDO NONATO DE SOUZA', 'SUPERVISOR DE MANUTENCAO'],
  ['002127', 'PAULO ROBERTO DE LIMA', 'SUPERVISOR DE CONSTRUCAO E MONTAGEM'],
  ['002461', 'RAIMUNDO NONATO DE OLIVEIRA', 'SUPERVISOR DE CALDEIRARIA'],
  ['002137', 'MARCIO BRAGA PACIFICO', 'SUPERVISOR DE AUTOMACAO E INSTRUMENTACAO'],
  ['002063', 'LENILSON ALVES DANTAS', 'SUPERVISOR DE MANUTENCAO'],
  ['002105', 'MARCELO MARCIO DOS SANTOS', 'SUPERVISOR DE MANUTENCAO'],
  ['002204', 'MARCIO JOSE FIGUEREDO', 'SUPERVISOR DE LOGISTICA'],
  ['002503', 'ARTHUR DIRCEU HENRIQUE DA SILVA', 'SUPERVISOR DE TRANSPORTE'],
  ['003094', 'PAULO CESAR DO ROSARIO FERNANDES', 'SUPERVISOR DE CONSTRUCAO E MONTAGEM'],
  ['600001', 'PEDRO MIZAEL OLIVEIRA DE SOUZA', 'SUPERVISOR DE PRODUCAO II'],
  ['600061', 'EDERSON BORGES PIRES', 'ENGENHEIRO DE SEGURANCA DO TRABALHO I'],
];

/**
 * Mapeia os dados brutos para o formato Employee da aplicação,
 * gerando o ID (Login) e Senha conforme a regra de negócio.
 */
export const EMPLOYEES: Employee[] = [
  ...RAW_EMPLOYEES_DATA.map(([mat, name, role]) => {
    // Stripping leading zeros: '001168' -> '1168'
    const strippedId = parseInt(mat, 10).toString();
    return {
      id: strippedId,
      name,
      role,
      password: strippedId // Regra: Matrícula sem zeros à esquerda como login e senha
    };
  }),
  // Mantendo supervisores técnicos e acessos de sistema previamente configurados
  { id: 'SUP001', name: 'Supervisor Geral Mossoró', role: 'Supervisor', password: 'prrecv' },
  { id: 'SUP002', name: 'Supervisor Geral Pendências', role: 'Supervisor', password: 'prrecv' },
  
  // Supervisores Fictícios adicionados para acesso por NOME
  { id: 'S100', name: 'Carlos Oliveira', role: 'Supervisor', password: 'prrecv' },
  { id: 'S101', name: 'Mariana Souza', role: 'Supervisor', password: 'prrecv' },
  { id: 'S102', name: 'Ricardo Silva', role: 'Supervisor', password: 'prrecv' },
  { id: 'S103', name: 'Ana Lucia', role: 'Supervisor', password: 'prrecv' },
];

export const ADMINS: Admin[] = [
  { id: 'luantorres', name: 'Luan Torres', role: 'MASTER', password: '1905' },
  { id: 'almoxarife', name: 'Almoxarife Local', role: 'COMMON', password: 'user123' },
];

// Função auxiliar para deduzir a unidade baseada na descrição (EPIs comuns)
const inferUnit = (description: string): string => {
  const d = description.toUpperCase();
  if (d.includes('LUVA') || d.includes('BOTA') || d.includes('CALÇADO') || d.includes('BOTINA') || d.includes('PERNEIRA') || d.includes('MANGOTE')) return 'PAR';
  if (d.includes('TRAVA QUEDA') || d.includes('TALABARTE') || d.includes('CINTO') || d.includes('MOSQUETÃO')) return 'UN';
  if (d.includes('METROS') || d.includes('CABO') || d.includes('CORDA')) return 'MT';
  return 'UN';
};

const RAW_MATERIALS_DATA = [
  ['241618170415304', 'CAPACETE ABA FRONTAL BRANCO'],
  ['23141180606234', 'CARNEIRA PARA CAPACETE MSA (CATRACA)'],
  ['23141180606201', 'CARNEIRA PARA CAPACETE MSA (SUSPENSÃO)'],
  ['24618152207091', 'CAPUZ DE SEGURANÇA EM ARAMIDA'],
  ['24618180206615', 'ÓCULOS DE SEGURANÇA INCOLOR EVOLUTION'],
  ['24618180215338', 'ÓCULOS DE SEGURANÇA PRETO EVOLUTION'],
  ['23141180606195', 'PROTETOR AURICULAR PLUG EM SILICONE'],
  ['24618190206619', 'PROTETOR AURICULAR TIPO CONCHA'],
  ['24618200215349', 'RESPIRADOR PFF2 – SEM VÁLVULA'],
  ['24618200207404', 'RESPIRADOR PFF2 – COM VÁLVULA'],
  ['24618150400148', 'LUVA DE PROTEÇÃO ABRASIVOS/CORTANTES (XG)'],
  ['24618150400143', 'LUVA DE PROTEÇÃO ABRASIVOS/CORTANTES (10/11)'],
  ['24618160406322', 'CALÇADO TIPO BOTA CANO MÉDIO (37)'],
  ['23141180607365', 'CALÇADO TIPO BOTA CANO MÉDIO (38)'],
  ['24618160406323', 'CALÇADO TIPO BOTA CANO MÉDIO (39)'],
  ['23141180607362', 'CALÇADO TIPO BOTA CANO MÉDIO (40)'],
  ['24618160406019', 'CALÇADO TIPO BOTA CANO MÉDIO (41)'],
  ['23141180607128', 'CALÇADO TIPO BOTA CANO MÉDIO (42)'],
  ['24618180606188', 'CINTO DE SEGURANÇA TIPO PARAQUEDISTA VICSA 20420'],
  ['23141180606204', 'TALABARTE SEGURANÇA DUPLO Y (110 mm)'],
];

export const MATERIALS: Material[] = RAW_MATERIALS_DATA.map(([sku, description]) => ({
  sku,
  description,
  unit: inferUnit(description),
  category: 'EPI'
}));
